<?php

namespace Database\Seeders;

use App\Models\Colegio;
use Illuminate\Database\Seeder;

class ColegioCochabambaSeeder extends Seeder
{
    public function run(): void
    {
        $nombres = [
            // Instituto JAC (siempre primero)
            'Instituto Tecnico JAC Bolivia 2000',
            // 254 Unidades Educativas con Secundaria - Capital Cochabamba
            // Fuente: SEIE - Ministerio de Educacion de Bolivia
            '1ro. de Mayo 2',
            '21 de Septiembre',
            '21 de Septiembre II',
            '23 de Marzo',
            '26 de Octubre',
            '29 de Septiembre',
            '4 de Marzo',
            '6 de Agosto',
            '8 de Mayo',
            '9 de Marzo',
            'Abaroa A',
            'Abaroa B',
            'Adela Zamudio A',
            'Adventista Cochabamba',
            'Aguilas de America',
            'Agustin Morales Hernandez',
            'Albert Einstein',
            'Alcides Arguedas A',
            'Alejo Calatayud',
            'Aleman Santa Maria',
            "Alto K'ara K'ara",
            'America del Sur',
            'Americano',
            'Americano Vecinal B',
            'Amor de Dios',
            'Amor de Dios Nocturno',
            'Ana Maria Romero de Campero',
            'Andres Bello',
            'Anglo Americano',
            'Anglo Japones',
            'Antonio Diez',
            'Arnoldo Schwimmer Gamza',
            'Atiy',
            'Augusto Guzman',
            'Ayacucho',
            'Ayni Pacha',
            'Bancaria',
            'Bartolina Sisa',
            'Bolivar',
            'Bolivia A',
            'Bolivia B',
            'Bolivia Holanda',
            'Boliviano Argentino',
            'Boliviano Croata',
            'Branko Petricevic D',
            'Brasil B',
            'Buena Vista Libertad A',
            'Buenas Nuevas C',
            'Buenas Nuevas D',
            'California',
            'Camara Junior C',
            'Canaan',
            'Capilla de Cochabamba',
            'Carlos Medinacelli',
            'Carmen Orruel de Verduguez',
            'Ceferino Namuncura',
            'Cendi',
            'Cobija',
            'Cobol',
            'Cochabamba',
            'Cochabamba A',
            'Compañia de Jesus',
            'Concordia',
            'Cosmos',
            'Daniel Salamanca Tarde',
            'Daniel Sanchez Bustamante',
            'Despertad',
            'Dionisio Morales Choque',
            'Domingo Faustino Sarmiento',
            'Domingo Savio',
            'Don Bosco',
            'Don Bosco B',
            'Dr. Demetrio Canelas Canelas',
            'Dr. Edgar Montaño Rivera',
            'Dr. Enrique Sanchez de Lozada Irigoyen',
            'Dr. Felix Capriles',
            'Edmundo Bojanowski A',
            'Edmundo Bojanowski B',
            'Eduardo Laredo',
            'Eduardo Lopez',
            'Eduardo Ocampo Moscoso',
            'Ejercito Cochabamba',
            'El Molino',
            'El Salvador',
            'Elena Arze de Arze',
            'Elizardo Perez',
            'Emanuel',
            'Enseñanza Cochabamba',
            'Esclavas del Sagrado Corazon de Jesus',
            'España',
            'Estados Unidos',
            'Eusebio Tudela Tapia I',
            'Eusebio Tudela Tapia II',
            'Evito',
            'Fatima',
            'Federico Aguilo',
            'Federico Froebel',
            'Felix del Granado',
            'Fidel Aranibar',
            'Francisco Gonzales Prada',
            'Francisco Javier Baldivieso Luna',
            'Franz Tamayo B',
            'Genoveva Rios',
            'Gerardo Vargas Vidal',
            'Geronimo de Osorio',
            'Gran Tunari II',
            'Gualberto Villarroel',
            'Heidi',
            'Heroes del Boqueron',
            'Hispano Boliviano',
            'Hno. Pacifico Feletti',
            'Humberto Portocarrero',
            'Innova Belen Arrumani',
            'Isaac Attie',
            'Ismael Montes',
            'Ismael Vasquez',
            'Italo Boliviano',
            'Jaime Escalante',
            'Jesus',
            'Jesus Lara',
            'Jesus Manuel Carmona',
            'John Dewey',
            'Jorge Cabrera Acuña',
            'Jose Antonio Arze',
            'Jose Carlos Carrillo',
            'Jose Quintin Mendoza',
            'Juan Crisostomo Carrillo',
            'Juan Lechin Oquendo',
            'Juana Azurduy de Padilla',
            'Juancito Pinto B',
            'Julio Jauregui',
            'Julio Mendez',
            'Junin',
            'La Edad de Oro',
            'La Salle',
            'La Salle A',
            'La Salle E',
            'Latinoamericano',
            'Laura Vicuña',
            'Libertad II',
            'Liborio Cadima',
            'Londres Continental',
            'Loyola',
            'Luis Espinal',
            'Luis Quintin Vila A',
            'Luz y Verdad',
            'Madre de la Divina Providencia',
            'Magic Kids Cala Cala',
            'Marcelo Quiroga Santa Cruz',
            'Maria Auxiliadora',
            'Maria Auxiliadora de Cristo Rey A',
            'Maria Ayma Mamani',
            'Maria Cristina',
            'Maria Josefa Mujia',
            'Mariano Antezana B',
            'Mariano Ricardo Terrazas',
            'Marina Nuñez del Prado',
            'Marista Secundaria',
            'Maryland',
            'Mejillones A',
            'Mercedes Candia de Ovando',
            'Micaela Bastidas',
            'Minero San Juan',
            'Misioneras de Cristo Jesus',
            'Napoleon Maldonado Vera',
            'Nordico Boliviano',
            'Nuestra Señora de la Merced A',
            'Nuestra Señora del Pilar',
            'Nueva Esperanza',
            'Nueva Vera Cruz',
            'Octavio Campero Echazu',
            'Oscar Alfaro Secundario',
            'Oscar Rojas Caballero',
            'Otto Felipe Braun',
            'Pacha',
            'Padre Luis Diez del Pozo',
            'Patria Nueva',
            'Paulo Freire',
            'Paulo VI',
            'Pedro Poveda',
            'Pedro Poveda Nocturno',
            'Peniel',
            'Pentecostal de Bolivia',
            'Petrolero Sanandita',
            'Pio XII',
            'Plurinacional San Isidro',
            'Prof. Jaime Alfonso Escalante Gutierrez',
            'Rafael Pabon Cuevas',
            'Rene Barrientos Ortuño A',
            'Rene Barrientos Ortuño C',
            'Republica de Venezuela',
            'Republica del Peru',
            'Rey de Reyes',
            'Ricardo Jaimes Freyre',
            'Richard Von Weizsacker',
            'Roberto Alvarado Daza',
            'Rosendo Peña',
            'Sagrada Familia',
            'Sagrado Corazon',
            'Sagrado Corazon de Jesus',
            'Saint Germain',
            'San Agustin',
            'San Andres',
            'San Antonio',
            'San Antonio de Pucara',
            'San Antonio Maria Claret',
            'San Francisco de Asis A',
            'San Francisco de Asis B',
            'San Francisco II',
            'San Francisco Javier',
            'San Joaquin A',
            'San Jose',
            'San Miguel',
            'San Nicolas',
            'San Pedro B',
            'San Rafael A',
            'San Rafael B',
            'San Vicente de Paul',
            'Santa Ana',
            'Santa Ana de Cala Cala Maryknoll',
            'Santa Elizabeth Seton',
            'Santa Luisa de Marillac',
            'Santa Maria Micaela',
            'Santa Maria Micaela A',
            'Santa Maria Micaela B',
            'Santa Teresa de Lisieux',
            'Santiago',
            'Santo Domingo de Guzman',
            'Santo Domingo Savio',
            'Santo Domingo Savio B',
            'Sara Ugarte de Salamanca',
            'Sebastian Pagador',
            'Señor de Mayo',
            'Sergio Almaraz Paz',
            'Shalom',
            'Siglo XX',
            'Stefano Hotellier',
            'Sucre',
            'Suecia',
            'Suizo Aleman',
            'Taquiña A',
            'Taquiña B',
            'Temporal',
            'Teodomiro Beltran',
            'Tiquirani',
            'Tupac Katari',
            'Venjanmin',
            'Verdad y Vida',
            'Victor Cabrera Lozada',
            'Vikinga Boliviana',
            'Vision Mundial',
            'Voces Libres',
            'Wilge Rodriguez B',
            'Yugoslavia',
        ];

        foreach ($nombres as $nombre) {
            Colegio::firstOrCreate(['nombre' => $nombre]);
        }
    }
}
